[package]
name = "trailbase-guest-common"
version = "0.8.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
hex.workspace = true
hmac.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
trailbase-wasm.workspace = true
url.workspace = true
