[package]
name = "trailbase-toss-identity"
version = "0.8.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
serde.workspace = true
trailbase-guest-common = { path = "../trailbase-guest-common", version = "0.8.0" }
trailbase-wasm.workspace = true
